apiVersion: apps/v1

kind: Deployment

metadata:

  creationTimestamp: null

  labels:

    app: hr-app

  name: hr-app

  namespace: a-adxamov

spec:

  replicas: 1

  selector:

    matchLabels:

      app: hr-app

  strategy: {}

  template:

    metadata:

      creationTimestamp: null

      labels:

        app: hr-app

    spec:

      containers:

       - image: nginx:1.18

         name: nginx


status: {}
